[build]
  # Build command - install dependencies and build from mixflow directory
  command = "npm install && npx nx build web-app --prod"

  # Directory with the static files (build output)
  publish = "dist/web-app"

  # Base directory for the build (the monorepo root)
  base = "mixflow"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  # Skip Nx Cloud to avoid connection issues
  NX_REJECT_UNKNOWN_LOCAL_CACHE = "0"

# SPA redirect rules - redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
